### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by MakenHubbard** [nss-evening-cohort-7/chatty-genuphobia#17]
# Story 
As a dev, In order to start the project, I need to set it up 

# Acceptance Criteria 
When the repository is cloned down 
Then I need to setup all the files for the project

# Technical Notes 
create index.html
create JS Folder
create main. js
create Styles Folder
create main.css
create Gruntfile.js
create Lib Folder
create .gitignore
create eslintrc.json

Close #17

**Comment by lolasimp** [comment]
😄

**Comment by AmandaM04** [comment]
Close #17
